version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Tehran
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
