export enum KycLevel {
  NONE = 'NONE',
  MOBILE_VERIFIED = 'MOBILE_VERIFIED',
  IDENTITY_VERIFIED = 'IDENTITY_VERIFIED',
  DOCUMENT_VERIFIED = 'DOCUMENT_VERIFIED',
  FACE_VERIFIED = 'FACE_VERIFIED',
  FULLY_VERIFIED = 'FULLY_VERIFIED',
}
